### PR TITLE
Setup script

### PR DESCRIPTION
**Pull request by EricRahm**
This adds a script that can be used to simplify the server setup process handling a few gotchyas I ran into setting the awsy clone. It intentionally leaves out setting up the crontab and nginx, which should probably be handled in a separate script.

### CODE REVIEW

**Comment by EricRahm** [comment]
@Nephyrin would you mind sanity checking this?

**Comment by Nephyrin** [comment]
r+

An optional nit, as someone who has run a lot of bootstrap-style scripts, I would prefer it if it prompted me for the commands it was going to run (esp since it has sudo):

    promptcmd() {
      echo >&2 "# $1:"
      echo >&2 $'\n'"+ $(printf "%q " "${@:2}")"$'\n'
      echo >&2 "  [ press enter to continue or control-c to abort ]"
      read || return
      "${@:2}"
    }
    
    promptcmd "Installing missing packages" \
              sudo apt-get install foo

    promptcmd "Making database directory" \
              mkdir "$AWSY/foo"

**Comment by EricRahm** [comment]
Sounds like a good improvement, I'll update the script.

**Comment by EricRahm** [comment]
I landed roughly as-is in 01eeb5438ff06b5060bd55db493e017bc37d9e58 and 38321258f7d7fd48cbee19f9b013e65b3c33cefe.

**Pull request closed without merging**
