### PR TITLE
Added documentation on how to use trywatcher #84

### PR DESCRIPTION
**Pull request by Ashwin02**
Resolves issue #84

### CODE REVIEW

**Comment by EricRahm** [comment]
@Ashwin02 Thank you for taking this on! The content looks good, but we actually generate the faq html from a markdown file: faq/faq.md

Can you update that file instead?

**Comment by Ashwin02** [comment]
Hello,

I am so sorry I was not aware about it. I have made the changes in faq.md and sent you a pull request. Please can you verify if everything is ok this time and feel free to ask me if you need to make anymore changes to it.
Also if there are any similar issues I would be happy to help.

Thank you.

**Comment by EricRahm** [comment]
@Ashwin02 It looks like you need to escape the `<` and `>` characters in the markdown file.

As to other similar bugs, there's another [documentation bug in mozdownload](https://github.com/mozilla/mozdownload/issues/309) which might might be of interest to you.

**Comment by Ashwin02** [comment]
@EricRahm I hope that solves the issue. Also thanks for pointing me to a similar bug.

**Comment by EricRahm** [comment]
@Ashwin02 Thank you for the contribution. I landed it with a minor format change in 732bfd59b389930b2dc9a67f587564f65dc6751b.

**Pull request closed without merging**
