### PR TITLE
Work arounds for various things that broke this month

### PR DESCRIPTION
**Pull request by EricRahm**
@Nephyrin can you do a quick review?

### CODE REVIEW

**Comment by EricRahm** [comment]
This is a bit of a rush job, @amccreight mind taking a look?

**Comment by amccreight** [comment]
r=me  How long is this FTP server going to be up? Have you talked to somebody involved with the FTP migration about AWSY?

**Comment by EricRahm** [comment]
I haven't talked to anyone directly, I'm going with the info from a dev-platform post: https://groups.google.com/d/msg/mozilla.dev.platform/FnAn_4a7Ohc/Y2MWq51BBgAJ

I think the end solution is probably to figure out what mozregression does and use that method.

**Comment by amccreight** [comment]
Last I heard, mozregression wasn't working. ;) But you should email the person who wrote that blog post and mention your use case so you can be kept in the loop.

**Pull request merged**
