### PR TITLE
Export e10s data

### PR DESCRIPTION
**Pull request by EricRahm**
This adds graphs for both e10s processes in arweslimyet. Fixing up the about:memory exporter will be done in a follow up.

@Nephyrin can you take a look?

### CODE REVIEW

**Comment by Nephyrin** [comment]
r=me

Does the "main" graph now only the parent, or is it combined? If it is only parent, having it be a continuation of what is formerly the combined graph doesn't seem quite right.

**Comment by EricRahm** [comment]
@Nephyrin I think if we just annotate it we'll be fine. Otherwise we'll need to either completely drop the old data or possibly move it to a separate tab (a la mobile).

**Comment by EricRahm** [comment]
And to answer your question it's only the parent.

**Comment by Nephyrin** [comment]
The other alternative would be to define some datapoints that combine their respective main+web content lines to carry on a single "combined" graph. I'm fine with either though, as long as it's deliberate.

**Comment by EricRahm** [comment]
I'll file a follow up for improving the display to provide some kind of combined metric (as well as annotation).

**Pull request merged**
